import { Geist, Geist_Mono } from "next/font/google";
import "../globals.css";
import SideMenu from "@/components/admin/SideMenu";
import Header from "@/components/admin/Header";
  import { ToastContainer } from 'react-toastify';


const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${geistSans.variable} ${geistMono.variable} antialiased`}
      >
        <main className="w-full min-h-screen flex">
          <ToastContainer
            position="top-right"
            autoClose={1000}
            hideProgressBar={false}
            newestOnTop={false}
            closeOnClick={false}
            rtl={false}
            pauseOnFocusLoss
            draggable
            pauseOnHover
            theme="colored"
          />
          <SideMenu />
          <div className="flex-1">
            <Header />
            <section className="p-4  bg-gray-50 h-screen">
              {children}
            </section>
          </div>
        </main>
      </body>
    </html>
  );
}
